#
#     (C) COPYRIGHT 2025   Al von Ruff
#       ALL RIGHTS RESERVED
#
#     The copyright notice above does not evidence any actual or
#     intended publication of such source code.
#


clean:
	rm -f *.cgi
	rm -f *.pyc
	rm -f .TARGETS

clobber:
	rm -f *.cgi
	rm -f *.pyc
