#
#     (C) COPYRIGHT 2026   Al von Ruff
#       ALL RIGHTS RESERVED
#
#     The copyright notice above does not evidence any actual or
#     intended publication of such source code.
#
#     Version: $Revision: 1240 $
#     Date: $Date: 2026-02-07 07:25:49 -0500 (Sat, 07 Feb 2026) $


lint:
	bash ../common/dolint.sh

